PROGRAM = dscStatus

# Include path to dscKeybusInterface-RTOS component.mk
EXTRA_COMPONENTS = $(abspath ../../../)

FLASH_SIZE ?= 32

# Include path to esp-open-rtos common.mk
include $(SDK_PATH)/common.mk
